vendorpage="//a[normalize-space()='Vendor Login']"
registration="//a[normalize-space()='Continue']"
terms="//input[@name='agree']"
submitbtn="//input[@value='Submit']"
displaynamelocator="//input[@id='input-display_name']"
firstnamelocator="//input[@id='input-firstname']"
lastnamelocator="//input[@id='input-lastname']"
emaillocatorvendor="//input[@id='input-email']"
phonelocator="//input[@id='input-telephone']"
address1locator="//input[@id='input-address-1']"
citylocator="//input[@id='input-city']"
city="Ghaziabad"
countrylocator="//select[@id='input-country']"
country="India"
zonelocator="//select[@id='input-zone']"
zone="Uttar Pradesh"
postcodelocator="//input[@id='input-postcode']"
postcode="201010"
address1="B-4/252, Gyan Khand 1"
passwordlocatorvendor="//input[@id='input-password']"
password2locatorvendor="//input[@id='input-confirm']"
storenamelocator="//input[@id='input-name1']"
descriptionlocator="//textarea[@id='input-meta_description1']"
paypal="//input[@id='input-paypal']"