allvendors="//span[normalize-space()='All Vendor']"
vendorstitle="//h4"
catalog="//li[@id='catalog']"
products="//a[normalize-space()='Products']"
addproduct="//a[@data-original-title='Add New']"
productnamelocator="//input[@id='input-name1']"
metatextloactor="//input[@id='input-meta-title1']"
datalocator="//a[normalize-space()='Data']"
modellocator="//input[@id='input-model']"
links="//a[normalize-space()='Links']"
attribute="//a[normalize-space()='Attribute']"
option="//a[@href='#tab-option']"
recurring="//a[@href='#tab-recurring']"
discount="//a[normalize-space()='Discount']"
special="//a[normalize-space()='Special']"
image="//a[normalize-space()='Image']"
reward="//a[normalize-space()='Reward']"
seo="//a[normalize-space()='SEO']"
design="//a[normalize-space()='Design']"
designdropdown="//select[@name='product_layout[0]']"
ddvalue="Home"
save="//button[@type='submit']"
success="//div[@class='alert alert-success']"
edit="css:.eyeicon"
inputpricelocator="//input[@id='input-price']"
inputprice="10098"
checkbox="(//input[@type='checkbox'])[2]"
delete="//button[@class='btn btn-danger']"