adminpanel="//a[normalize-space()='Admin Login']"
usernamelocator="//input[@id='input-username']"
usernameadmin="demoadmin"
passwordadmin="demopass"
passwordlocator="//input[@id='input-password']"
loginbtnadmin="css:.btn"
dashboardtxt="Dashboard"
logoutadmin="//span[contains(text(),'Logout')]"
admin_catalog="//a[normalize-space()='Catalog']"
admin_products="//a[normalize-space()='Products']"
admin_categories="//a[normalize-space()='Categories']"
deletebtn="css:.btn-danger"
deletealert="css:.alert-danger"