registration="xpath=//a[normalize-space()='Continue']"
firstnamelocator="xpath=//input[@id='input-firstname']"
lastnamelocator="xpath=//input[@id='input-lastname']"
emaillocator="xpath=//input[@id='input-email']"
phonelocator="xpath=//input[@id='input-telephone']"
passwordlocator="xpath=//input[@id='input-password']"
password2locator="xpath=//input[@id='input-confirm']"
terms="xpath=//input[@name='agree']"
continuebtn="xpath=//input[@value='Continue']"
logoutelement="xpath=//span[@id='cartme']"
passwordInvalid="xxxxxxxxxx"
custloginbtn="//input[@value='Login']"
danger="//div[@class='alert alert-danger alert-dismissible']"