homepageelement="css:.fa.fa-home"
womenscard="//div[@class='owl-item active']//h5//a[contains(text(),'Women')]"
cardtitle="css:.protitle"
# carticon="xpath://span[normalize-space()='Items']"
carticon="xpath:(//button[@data-toggle='dropdown'])[3]"
viewcart="xpath://a[normalize-space()='View Cart']"
items_in_cart="css:.cart-des-name"
checkoutbtn="//div[@class='pull-right']//a[@class='btn btn-primary'][normalize-space()='Checkout']"
popup="css:.alert.alert-success.alert-dismissible.alertsuc"
address1="B-4/252, Gyan Khand 1"
address2="Indirapuram"
city="Ghaziabad"
pincode="201010"
countrydata="India"
regiondata="Uttar Pradesh"
firstnamelocator="//input[@id='input-payment-firstname']"
lastnamelocator="//input[@id='input-payment-lastname']"
address1locator="//input[@id='input-payment-address-1']"
address2locator="//input[@id='input-payment-address-2']"
citylocator="//input[@id='input-payment-city']"
pincodelocator="//input[@id='input-payment-postcode']"
countrylocator="//select[@id='input-payment-country']"
regionlocator="//select[@id='input-payment-zone']"
shippingaddresbtn="//input[@id='button-shipping-address']"
paymentaddressbtn="//input[@id='button-payment-address']"
shippingmethodbtn="//input[@id='button-shipping-method']"
terms="//input[@name='agree']"
paymentmethodbtn="//input[@id='button-payment-method']"
confirmorderbtn="//input[@value='Confirm Order']"
cardbtn="//button[@method='card']"
cod="//input[@value='cod']"
successtext="Your order has been successfully processed!"
editprofile="//a[normalize-space()='Edit Account']"
editprofiletext="My Account Information"
phoneupdatelocator="//input[@id='input-telephone']"
newphonevalue="9876543210"
continuebtn="//input[@value='Continue']"
successalertupdate="css:.alert"
address_group="payment_address"
address_value="new"